version: '3.7'
services:
  #mongo DB
  db1:
    image: mongo
    ports:
      - "27016:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
  # Postgresql
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - PG_PRIMARY_USER= postgres
      - PG_PRIMARY_PASSWORD= my-secret-password
      - POSTGRES_PASSWORD=rahadian1997
      - POSTGRES_DB=motor
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=your-email@example.com
      - PGADMIN_DEFAULT_PASSWORD=your-secret-password
  # mongo express
  webui:
    image: mongo-express
    ports:
      - "9015:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root123
      - ME_CONFIG_MONGODB_SERVER=db1
  #Kafka
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka-manager:
    image: obsidiandynamics/kafdrop
    hostname: kafka-manager
    ports:
      - "9010:9000"
    environment:
      - KAFKA_BROKER_CONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    depends_on:
      - zookeeper
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  db_data:
    driver: local
